apiVersion: v2
name: uptime-kuma-operator
description: Syncs Uptime Kuma monitors from Ingress, HTTPRoute, and a Monitor CRD
type: application
version: 0.2.1
appVersion: "main"
kubeVersion: ">=1.23.0-0"
keywords:
  - uptime-kuma
  - monitoring
  - operator
  - kubernetes-operator
home: https://github.com/Roxxas96/uptime-kuma-operator
sources:
  - https://github.com/Roxxas96/uptime-kuma-operator
maintainers:
  - name: Alexandre Gomez
